# From https://gitlab.com/CLIUtils/modern-cmake/-/blob/b47192867e86e5f00f70ec860638a28473edc8bf/examples/extended-project/src/CMakeLists.txt

# Note that headers are optional, and do not affect add_library, but they will not
# show up in IDEs unless they are listed in add_library.

# Optionally glob, but only for CMake 3.12 or later:
# file(GLOB HEADER_LIST CONFIGURE_DEPENDS "${codac_SOURCE_DIR}/include/modern/*.hpp")
#set(HEADER_LIST "${codac_SOURCE_DIR}/include/modern/lib.hpp")
#set(SOURCE_LIST 
#codac.cpp
#)
#file(GLOB HEADER_LIST CONFIGURE_DEPENDS "${codac_SOURCE_DIR}/codac/*.h" "${codac_SOURCE_DIR}/codac/*.hpp")
#file(GLOB OTHER_LIST CONFIGURE_DEPENDS "${codac_SOURCE_DIR}/codac/*.ypp")

# Make an automatic library - will be static or dynamic based on user setting
#add_library(codac ${SOURCE_LIST} ${HEADER_LIST} ${OTHER_LIST})

#file(GLOB_RECURSE CODAC_GRAPHICS_SRC CONFIGURE_DEPENDS 
#    "${CMAKE_CURRENT_SOURCE_DIR}/*.cpp"
#    "${CMAKE_CURRENT_SOURCE_DIR}/*.h"
#)

  list(APPEND CODAC_GRAPHICS_SRC
    
    ${CMAKE_CURRENT_SOURCE_DIR}/3rd/ipe/codac2_Figure2D_IPE.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/3rd/ipe/codac2_Figure2D_IPE.h
    ${CMAKE_CURRENT_SOURCE_DIR}/3rd/vibes/codac2_Figure2D_VIBes.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/3rd/vibes/codac2_Figure2D_VIBes.h
    ${CMAKE_CURRENT_SOURCE_DIR}/3rd/vibes/vibes.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/3rd/vibes/vibes.h

    ${CMAKE_CURRENT_SOURCE_DIR}/figures/codac2_Figure2D.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/figures/codac2_Figure2D.h
    ${CMAKE_CURRENT_SOURCE_DIR}/figures/codac2_Figure2DInterface.h
    ${CMAKE_CURRENT_SOURCE_DIR}/figures/codac2_OutputFigure2D.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/figures/codac2_OutputFigure2D.h
    ${CMAKE_CURRENT_SOURCE_DIR}/figures/codac2_Figure3D.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/figures/codac2_Figure3D.h

    ${CMAKE_CURRENT_SOURCE_DIR}/paver/codac2_drawwhilepaving.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/paver/codac2_drawwhilepaving.h

    ${CMAKE_CURRENT_SOURCE_DIR}/styles/codac2_Color.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/codac2_Color.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/codac2_ColorMap.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/codac2_ColorMap.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/codac2_StyleProperties.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/codac2_StyleProperties.h
  )

# Make an automatic library - will be static or dynamic based on user setting
add_library(codac-graphics ${CODAC_GRAPHICS_SRC})

# We need this directory, and users of our library will need it too
#target_include_directories(codac PUBLIC ../include)
# Inspired from https://unclejimbo.github.io/2018/06/08/Modern-CMake-for-Library-Developers/
target_include_directories(codac-graphics 
	PUBLIC
		"$<INSTALL_INTERFACE:include>"
		"$<BUILD_INTERFACE:${PROJECT_BINARY_DIR}>"
		"$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>"
        "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/3rd/ipe>"
        "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/3rd/vibes>"
        "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/figures>"
        "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/paver>"
        "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/styles>"
)

# See https://github.com/friendlyanon/cxx-static-shared-example
include(GenerateExportHeader)
generate_export_header(
    codac-graphics
    BASE_NAME codac-graphics
    EXPORT_FILE_NAME codac-graphics_export.h
)

target_link_libraries(codac-graphics PUBLIC codac-core gaol::gaol Eigen3::Eigen)

if(NOT BUILD_SHARED_LIBS)
  target_compile_definitions(codac-graphics PUBLIC codac_STATIC_DEFINE)
else()
  target_compile_definitions(codac-graphics PUBLIC codac_SHARED_DEFINE) # For compatibility...
endif()

# TO CHECK DEFAULTS DEPENDING ON THE COMPILER, ALSO THE .CMAKE...



target_compile_features(codac-graphics PUBLIC cxx_std_20)



# Getting header files from sources

  foreach(srcfile ${CODAC_GRAPHICS_SRC})
    if(srcfile MATCHES "\\.h$" OR srcfile MATCHES "\\.hpp$")
      list(APPEND CODAC_GRAPHICS_HDR ${srcfile})
      file(COPY ${srcfile} DESTINATION ${PROJECT_BINARY_DIR}/../../include)
    endif()
  endforeach()

# Generating the file codac-graphics.h

  set(CODAC_GRAPHICS_MAIN_HEADER ${PROJECT_BINARY_DIR}/codac-graphics.h)
  set(CODAC_MAIN_SUBHEADERS ${CODAC_MAIN_SUBHEADERS} "codac-graphics.h" PARENT_SCOPE)
  file(WRITE ${CODAC_GRAPHICS_MAIN_HEADER} "/* This file is generated by CMake */\n\n")
  file(APPEND ${CODAC_GRAPHICS_MAIN_HEADER} "#pragma once\n\n")
  foreach(header_path ${CODAC_GRAPHICS_HDR})
    get_filename_component(header_name ${header_path} NAME)
    if((NOT header_name MATCHES "^.*_addons.*$") AND (NOT header_name MATCHES "^.*_impl.*$"))
      file(APPEND ${CODAC_GRAPHICS_MAIN_HEADER} "#include <${header_name}>\n")
    endif()
  endforeach()
  file(COPY ${CODAC_GRAPHICS_MAIN_HEADER} DESTINATION ${PROJECT_BINARY_DIR}/../../include)


# Install files in system directories

if (CODAC_INSTALL)
  install(FILES ${CODAC_GRAPHICS_HDR} DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/codac-graphics)
  install(FILES ${CODAC_GRAPHICS_MAIN_HEADER} DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/codac-graphics)
endif()


# IDEs should put the headers in a nice place
#source_group(
#  TREE "${PROJECT_SOURCE_DIR}/include"
#  PREFIX "Header Files"
#  FILES ${HEADER_LIST})
#source_group(
#  TREE "${PROJECT_SOURCE_DIR}/graphics"
#  PREFIX "Other Files"
#  FILES ${OTHER_LIST})
