
list(APPEND CODAC_CAPD_SRC
    
  ${CMAKE_CURRENT_SOURCE_DIR}/codac2_capd.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/codac2_capd.h
)
  
# Make an automatic library - will be static or dynamic based on user setting
#add_library(${PROJECT_NAME}-capd ${CODAC_CAPD_SRC} ${CODAC_CAPD_HDR})
add_library(${PROJECT_NAME}-capd ${CODAC_CAPD_SRC})
  
 # Inspired from https://unclejimbo.github.io/2018/06/08/Modern-CMake-for-Library-Developers/
target_include_directories(${PROJECT_NAME}-capd 
	PUBLIC
		"$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}/${PROJECT_NAME}-capd>"
		"$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>"
		"$<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}>"
		"$<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}/..>"
		"$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>"
)

# See https://github.com/friendlyanon/cxx-static-shared-example
include(GenerateExportHeader)
generate_export_header(
    codac-capd
    BASE_NAME codac-capd
    EXPORT_FILE_NAME codac-capd_export.h
)

target_link_libraries(${PROJECT_NAME}-capd PUBLIC ${PROJECT_NAME}-core ${PROJECT_NAME}-eigen gaol::gaol capd::capd) #Eigen3::Eigen

if(NOT BUILD_SHARED_LIBS)
  target_compile_definitions(${PROJECT_NAME}-capd PUBLIC codac_STATIC_DEFINE)
else()
  target_compile_definitions(${PROJECT_NAME}-capd PUBLIC codac_SHARED_DEFINE) # For compatibility...
endif()

# TO CHECK DEFAULTS DEPENDING ON THE COMPILER, ALSO THE .CMAKE...



target_compile_features(${PROJECT_NAME}-capd PUBLIC cxx_std_20)




  ################################################################################
  # Installation of libcodac-capd files
  ################################################################################

  # Getting header files from sources

  foreach(srcfile ${CODAC_CAPD_SRC})
    if(srcfile MATCHES "\\.h$" OR srcfile MATCHES "\\.hpp$")
      list(APPEND CODAC_CAPD_HDR ${srcfile})
      file(COPY ${srcfile} DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/../../../include)
    endif()
  endforeach()

  # Generating the file codac-capd.h

  set(CODAC_CAPD_MAIN_HEADER ${CMAKE_CURRENT_BINARY_DIR}/codac-capd.h)
  file(WRITE ${CODAC_CAPD_MAIN_HEADER} "/* This file is generated by CMake */\n\n")
  file(APPEND ${CODAC_CAPD_MAIN_HEADER} "#pragma once\n\n")
  foreach(header_path ${CODAC_CAPD_HDR})
    get_filename_component(header_name ${header_path} NAME)
    file(APPEND ${CODAC_CAPD_MAIN_HEADER} "#include <${header_name}>\n")
  endforeach()
  file(COPY ${CODAC_CAPD_MAIN_HEADER} DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/../../../include)

  # Install files in system directories

 
  
  
  
if (CODAC_INSTALL)
  install(TARGETS ${PROJECT_NAME}-capd DESTINATION ${CMAKE_INSTALL_LIBDIR})


  install(FILES ${CODAC_CAPD_HDR} DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/${PROJECT_NAME}-capd)
  install(FILES ${CODAC_CAPD_MAIN_HEADER} DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/${PROJECT_NAME}-capd)
endif()
